### ISSUE TITLE
Performance degradation compared to MoonSharp

### ISSUE THREAD

**Issue by martindeveloper** [WattleScript/wattlescript#63]
Hello,

First of all - thank you very much for pushing Lua in C# further!

Right know I'm investigating use of Lua in my project where performance and safety is critical and `MoonSharp` seems to be without update for some time and `WattleScript` came to my attention that includes some fixes as well as some features which may help performance like dumping and loading byte code.

So I have created a simple "benchmark" to compare speeds of `MoonSharp` and `WattleScript` and seems like the `WattleScript` is about **25% slower** - is this expected due some internal safety measures or am I doing something wrong (yes the benchmark does not use bytecode caching, but that's on purpose)?

Code is here https://gist.github.com/martindeveloper/82102c2e52898bc7a203a6e21a66bdc2 and it is very close to my goal - running same script many times only with different input value.

Testing with .NET 7.0.100 on Apple M2 Max CPU using `dotnet run --configuration Release` command.

Example output on my machine is following

```
MoonSharp took 41ms with 10000 iterations
WattleScript took 64ms with 10000 iterations
```

Thank you.

**Comment by CallumDev** [comment]
Hi,

I've just pushed a commit ( 34e859c ) that should address this, and hopefully put WattleScript ahead in performance again. Please give it a go and let me know if it helps

For both WattleScript and Moonsharp, however, I don't recommend calling methods with a Dictionary as a parameter. The behaviour there is to convert the Dictionary into a lua table, which has allocation and copying costs. Particularly with WattleScript, the structure is optimised for faster indexing and iteration with lua semantics, sacrificing some of the speed when converting from .NET dictionaries as a tradeoff. The better way to do it is to pass a plain class instead, or you can wrap your dictionary in a class with an indexer if it is readonly - which gives WattleScript the opportunity to have more efficient interop.

**Comment by martindeveloper** [comment]
Hello,

Thank you for your reply! Will try with the provided commit.

About the dictionaries - sadly in our use-case we do not know before hand the data structures as well as scripts.

Generally our users are able to provide any data (JSON/XML/whatever) which are converted to dictionaries and passed as argument to Lua scripts for user defined processing. The dictionaries are meant to be readonly, as the results are stored in different structures, so possible wrapping the dictionary into class with indexer as you suggested may help.

**Comment by CallumDev** [comment]
Closing since I'm fairly sure 34e859c fixes the reported issue
