### ISSUE TITLE
Unity 2022.2.12 IL2CPP android build failed

### ISSUE THREAD

**Issue by shpitsmedia** [WattleScript/wattlescript#67]
Unity 2022.2.12 IL2CPP android build failed:

error: cannot convert 'Nullable_***' to 'int32_t' (aka 'int') without a conversion operator
bool L_44 = il2cpp_codegen_enum_has_flag((int32_t)L_40, (int32_t)L_43);

Probably IL2CPP bug but maybe you could point us to the right direction?

Cheers.

**Comment by CallumDev** [comment]
This does look a little bit like an IL2CPP bug as this is definitely all valid C#.

My guess is this comes from MemberConflicts.cs, on line 16 there is a `MemberModifierFlags?`. Can you check if removing the question mark from that line fixes your IL2CPP error?

**Comment by CallumDev** [comment]
Moved second issue to #68
